### ISSUE TITLE
Suggestion: Add lasso selection functionality to Form Labeling tool 

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#120]
copied from https://cognitive.uservoice.com/forums/921556-form-recognizer/suggestions/39850153-add-lasso-selection-functionality-to-form-labeling

It would be really nice to have a "Lasso" selection functionality in the form labeling tool. I know I can hold the left mouse button down to highlight multiple words but there are some areas of forms (e.g. remarks) where we have several hundred words that have to be selected. They usually are in a rectangle shape so hence a lasso selection would work perfectly.

**Comment by stew-ro** [comment]
Users can initiate drawing a lasso for multi selection by holding down the shift key
