### ISSUE TITLE
Suggestion: Copy fields to another project

### ISSUE THREAD

**Issue by iMicknl** [microsoft/OCR-Form-Tools#155]
**Is your feature request related to a problem? Please describe.**
When working on multiple models with the same fields, it is a hassle to create them over and over again. I have tried copying the fields.json to another project, however that file will be overwritten with an empty one directly..

**Describe the solution you'd like**
A method to copy fields to another model project, or at least the possibility to upload it on the blob storage.

**Comment by iMicknl** [comment]
It looks like it only works when you have the fields.json already in the folder, before actually creating and opening the project.

```
     * Assign project tags
     * A new project does not have any tags at the beginning. But it could connect to a blob container
     * Which contains existing fields .json file. In this case, we'll populate project tags base on this file.
```
https://github.com/microsoft/OCR-Form-Tools/blob/4915562a6146424a54559e83d3eaa7415283a914/src/services/projectService.ts#L230

**Comment by stew-ro** [comment]
Copying fields.json to another folder was supported in ef18425. After ef18425 all projects read from the folder's field.json and update their fields

**Comment by kunzms** [comment]
Close this issue as it is supported now.
