### ISSUE TITLE
have version number linking to the change log file

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#186]
make the version number in the bottom-right corner a clickable link, 
 pointing to https://github.com/microsoft/OCR-Form-Tools/blob/master/CHANGELOG.md

**Comment by jackspyder** [comment]
Would be nice if we could have git tag/releases to match, a long with the matching tag on the docker image please and thank you!

**Comment by jackspyder** [comment]
> > Would be nice if we could have git tag/releases to match, a long with the matching tag on the docker image please and thank you!
> 
> I'd like to understand the benefit of using docker image, compared to building your own, and use https://fott.azurewebsites.net/. is there a situation where using docker image is the only choice?

Hosting the service in an internal only AKS cluster. We could build our own image, just this was previously provided before going open source. As for building our own image, it would be good if at the least, we could get proper github releases/tags as targets for building images against.

**Comment by kunzms** [comment]
We put a link to github commit in the version number. Let us know if it resolved this issue.
