### ISSUE TITLE
FOTT bug report - Reordering a tag quickly does not work

### ISSUE THREAD

**Issue by olivierdolle** [microsoft/OCR-Form-Tools#193]
**Describe the bug**
In the `Tags editor` page, I have around 20+ tags and want to reorder one that is at the bottom of the tag list for labelling efficiency.
When I click on the arrow to reorder it several times in a row the tag doesn't go at all where expected.
It renders the reordering of labels for project with large number of label practically undoable.

**To Reproduce**
1. Go to `Tags Editor` page
2. Create around 10 tags
3. Select a tag at the bottom of the list and try to move it up to first place
4. See that the tag moves up and down on its own for a few seconds after last clicking on the `Move Tag up` arrow

**Expected behavior**
Reordering of tags working smoothly

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Docker version: Docker Desktop Community 2.2.0.5
 - Browser: firefox
 - Version : latest docker image (ImageId: `23ba43da7425`)

**Additional context**
Azure Storage is in France Central, Form Recognizer in West Europe

**Comment by xinase** [comment]
are you using the docker version of the tool,  or the https://fott.azurewebsites.net  site? or you build this tool by the latest source code?

thanks

**Comment by olivierdolle** [comment]
Latest docker version, the image id is under Desktop > Version of the bug report (didn't know what to put there :/ )

**Comment by olivierdolle** [comment]
Didn't see the latest image was 4 week old, I'll check and give you an update with the latest version of the code.

**Comment by olivierdolle** [comment]
Doesn't work either on master outside of docker.

I checked the http calls emitted when moving a tag up and down.
It happens in my case, several `PUT` are sent concurrently and the order in which they end is not the order in which they where emitted thus my label is updated and reordered seemingly randomly.

**Comment by xinase** [comment]
then we will take a close look
