### ISSUE TITLE
FOTT bug report - Deselect tag content doesn't work

### ISSUE THREAD

**Issue by iMicknl** [microsoft/OCR-Form-Tools#196]
**Describe the bug**
After you have set the tag for a highlighted part of text, it can not be removed easily.

**To Reproduce**
1. Highlight a part of the text
2. Apply the text to a tag
3. Try to remove the selected words from this tag, without reapplying it to another tag.

**Expected behavior**
Have a way to clear a tag, without deleting the tag. Currently I assign the selected text to another new tag, which I than remove. This should be way easier.

**Desktop (please complete the following information):**
 - OS: Mac
 - Docker version: latest 1.0.0 and 2.0.0-202fb2f
 - Browser: Edge Chromium Canary (Mac)
 - Version: 84.0.488.0

**Comment by stew-ro** [comment]
Currently, we support removing tagged values from a tag by selecting the tagged values on the image and using the 'backspace' key. 

We'll look into making this more intuitive for users

**Comment by iMicknl** [comment]
Thanks! Knowing it works with backspace makes it way easier already, would be good to have that one documented somewhere. Or to add something like a 'keyboard shortcut overlay', which you can toggle. 

![image](https://user-images.githubusercontent.com/1424596/79801060-b29c3400-835d-11ea-9c01-41bcf20f1b62.png)

**Comment by xinase** [comment]
good idea

**Comment by iMicknl** [comment]
By the way; Teams also has a keyboard shortcuts modal built-in. https://support.office.com/en-us/article/keyboard-shortcuts-for-microsoft-teams-2e8e2a70-e8d8-4a19-949b-4c36dd5292d2

<img width="800" alt="Screenshot 2020-05-14 at 20 02 43" src="https://user-images.githubusercontent.com/1424596/81969232-e34e5100-961d-11ea-82fb-7876db01a4de.png">

**Comment by alex-krasn** [comment]
closed in #258
