### ISSUE TITLE
FOTT bug report: everything after '_' or '-' was cut off in connection/project names

### ISSUE THREAD

**Issue by kunzms** [microsoft/OCR-Form-Tools#226]
**Describe the bug**

**To Reproduce**
1. Create a project/connection with '-' or '_' inside the name
2. Everything after '-' or '_' was cut off

**Expected behavior**
'-' or '_' should be supported in connection/project name

**Comment by alex-krasn** [comment]
Need more details. Not been able to reproduce. 
Look at screenshots:
<img width="330" alt="Screen Shot 2020-05-04 at 12 29 54 PM" src="https://user-images.githubusercontent.com/64093224/81005568-064d5980-8e03-11ea-9c48-178da2bad109.png">

<img width="1112" alt="Screen Shot 2020-05-04 at 11 59 40 AM" src="https://user-images.githubusercontent.com/64093224/81005456-d3a36100-8e02-11ea-8051-90664bc697f3.png">
