### ISSUE TITLE
Split pane overlapping with asset preview scrollbar

### ISSUE THREAD

**Issue by stew-ro** [microsoft/OCR-Form-Tools#250]
**Describe the bug**
The split pane overlaps with the asset preview scrollbar. This makes clicking the asset preview scrollbar difficult  

**To Reproduce**
1. Go to editor page
2. Click on scrollbar section that overlaps with split pane

**Expected behavior**
Split pane does not overlap with asset preview scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/60453211/81614821-7759b780-9395-11ea-8c36-0bcbd6ffe869.png)

**Comment by alex-krasn** [comment]
fis is here: https://github.com/microsoft/OCR-Form-Tools/pull/252
