### ISSUE TITLE
enable re-generate OCR for a single file, or for all files

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#256]
**Is your feature request related to a problem? Please describe.**
sometimes people need to re-generate OCR for a file,  for now,  user has to delete the .ocr.json file in the blob storage account,  which is not ease to do. 

**Describe the solution you'd like**
enable re-generate OCR for a single file, or for all files

**Comment by alex-krasn** [comment]
Closed in #297
