### ISSUE TITLE
Use "Esc" key to close Keyboard shortcuts and table popups/views

### ISSUE THREAD

**Issue by stew-ro** [microsoft/OCR-Form-Tools#274]
**Is your feature request related to a problem? Please describe.**
Support user ability to close Keyboard shortcuts and table popups/views with the "Esc" key

**Describe the solution you'd like**
When user presses "Esc" key, popup/view closes

**Describe alternatives you've considered**
Currently, the user has to use the pointer to close view

**Additional context**

**Comment by alex-krasn** [comment]
closed with 2e994f5
