### ISSUE TITLE
Displaying invalid mime type warning for valid PNG

### ISSUE THREAD

**Issue by stew-ro** [microsoft/OCR-Form-Tools#278]
**Describe the bug**
Getting invalid mime type warning on valid PNG file. PNG file has header 0x89504e47

**To Reproduce**
1. Upload valid png with 0x89504e47 header to azure blob container of existing project
2. Go to editor page

**Expected behavior**
No warning should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/60453211/82946106-a43fca00-9f52-11ea-95ce-3d9689ab1ca9.png)

**Comment by alex-krasn** [comment]
closed in #291
