### ISSUE TITLE
FOTT bug report: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by alex-krasn** [microsoft/OCR-Form-Tools#293]
**Describe the bug**
When switching between documents rapidly by clicking on preview sidebar after ~3rd document the app gets error - the app doesn't crashes but shows the error.
**To Reproduce**
1. Open multi document project
2. Start clicking through the documents on preview sidebar
3. After 3-4 documents the crashes

**Expected behavior**
No crashes
**Screenshots**
![image](https://user-images.githubusercontent.com/64093224/83444273-03448980-a400-11ea-8f0a-b57c1a6584b3.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser [Edge, Chrome]

**Comment by cdolan92** [comment]
This appears to be happening if you go to page 3 of any document in the viewer?
