### ISSUE TITLE
Support local filesystem as connection

### ISSUE THREAD

**Issue by Hhessling** [microsoft/OCR-Form-Tools#326]
Like Vott, which already supports lokal filesystem as connection, it would be nice to support it here as well.

**Comment by ahaw021** [comment]
I believe this is possible if you build locally

![image](https://user-images.githubusercontent.com/26753809/86881690-36cab000-c132-11ea-9445-dc37e063be32.png)

**Comment by stew-ro** [comment]
Yes, on premise solutions were supported with #361 . Like @ahaw021 noted, you can start the on premise solution with `yarn start` or `yarn react-start && electron-start`. 

Another option is to create a distributable desktop application with `yarn release` and use that
