### ISSUE TITLE
Build command fails due to invalid version number

### ISSUE THREAD

**Issue by ZeanQin** [microsoft/OCR-Form-Tools#340]
**Describe the bug**
Invalid version number in `package.json`

**To Reproduce**
1. Run `npm run build`

**Expected behavior**
The program builds successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/971174/85642675-84c4ca00-b6d5-11ea-9f5b-520bf3f89e6b.png)

**Desktop (please complete the following information):**
 - OS: [Win10/WSL V1]

**Comment by stew-ro** [comment]
`yarn build` works as an alternative. We'll work on resolving this issue for npm
