### ISSUE TITLE
FOTT bug report: Model compose scrollbar always has extra scroll space

### ISSUE THREAD

**Issue by tianxiangs** [microsoft/OCR-Form-Tools#351]
**Describe the bug**
Model compose scrollbar always has extra scroll space

**Screenshots**
![scrollbar_extra_space](https://user-images.githubusercontent.com/60452964/85808069-aab79200-b708-11ea-9c41-29e26533517d.png)

**Comment by alex-krasn** [comment]
This is not present anymore. The scroll bar is for the models list - and it displays properly.
<img width="1166" alt="Screen Shot 2020-07-06 at 10 05 13 AM" src="https://user-images.githubusercontent.com/64093224/86619866-31be0300-bf70-11ea-9ea6-8b5a0f363e0b.png">
