### ISSUE TITLE
FOTT bug report: User could analyze with model which is not ready 

### ISSUE THREAD

**Issue by tianxiangs** [microsoft/OCR-Form-Tools#353]
**Describe the bug**
User could analyze with model which is not ready

**To Reproduce**
1. Go to model compose page and compose a new model 
2. Go to the analyze page to predict just finish composing.
3. Sometimes new composed model will still not be ready and will cause unexpected predict result.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Linux-flavor]
 - Docker version

**Additional context**
Add any other context about the problem here. e.g, your Azure Resource region

**Comment by alex-krasn** [comment]
closed in #369
