### ISSUE TITLE
FOTT bug report: "User aborted request" error 

### ISSUE THREAD

**Issue by tianxiangs** [microsoft/OCR-Form-Tools#354]
**Describe the bug**
"User aborted request" error when scrolling document previews fast. And, also randomly

**To Reproduce**
It will cause randomly when scrolling document previews pretty fast

**Screenshots**
![user_abort](https://user-images.githubusercontent.com/60452964/85808305-4b0db680-b709-11ea-8751-f64dae03fc5c.jpg)

**Comment by stew-ro** [comment]
This issue seems to have been resolved with 7192170 by upgrading the pdfjs worker used. @alex-krasn can you help verify
