### ISSUE TITLE
FOTT bug report: User isn't notified that current project's model changes after clicking "compose"

### ISSUE THREAD

**Issue by tianxiangs** [microsoft/OCR-Form-Tools#355]
**Describe the bug**
User isn't notified that current project's model changes after clicking "compose"

**Screenshots**
![missing_notification](https://user-images.githubusercontent.com/60452964/85808728-9e343900-b70a-11ea-8e5e-2319a989dbc0.png)

**Comment by alex-krasn** [comment]
closed in #369
