### ISSUE TITLE
FOTT bug report: Wrong typo

### ISSUE THREAD

**Issue by tianxiangs** [microsoft/OCR-Form-Tools#357]
**Describe the bug**
Wrong typo in project

1. "Compose" should be "composed" and lower case
![compose_wrong_typo](https://user-images.githubusercontent.com/60452964/85808979-5235c400-b70b-11ea-9547-90af32753f38.png)

2. "Model is loading" should be "Loading models" (plural)
![model_loading_typo](https://user-images.githubusercontent.com/60452964/85809014-6ed1fc00-b70b-11ea-8496-4698fc126406.png)

3. Compose "Find By Name" should be lower case after first letter
![filter_field_typo](https://user-images.githubusercontent.com/60452964/85809065-95903280-b70b-11ea-980e-212d9484e679.png)

**Comment by alex-krasn** [comment]
fixed in #364
