### ISSUE TITLE
FOTT bug report: compose icon disappearing from after view change

### ISSUE THREAD

**Issue by alex-krasn** [microsoft/OCR-Form-Tools#367]
**Describe the bug**
"composed model" disappearing after change view or reload
**To Reproduce**
1. Compose new model
2. Leave the view or close browser window
3. Come back to compose models view
4. See error - there is not icon anymore on composed model

**Expected behavior**
"Composed model" icon should persist
**Screenshots**
![Screen Shot 2020-06-29 at 11 32 27 AM](https://user-images.githubusercontent.com/64093224/86043021-ec905300-b9fc-11ea-8067-8c8eca37d07f.png)
![Screen Shot 2020-06-29 at 11 33 32 AM](https://user-images.githubusercontent.com/64093224/86043025-eef2ad00-b9fc-11ea-8030-e76aa9c7df9f.png)

**Additional context**
Add any other context about the problem here. e.g, your Azure Resource region

**Comment by stew-ro** [comment]
Currently, the back-end service for getting models doesn't return the model info required to resolve this issue. So, for now, we're only showing the composed icon only after initial composing action.

**Comment by stew-ro** [comment]
This issue was resolved with 18fb4d71052b9355c8d5a4f7dde956ba17ca30fa
