### ISSUE TITLE
FOTT bug report: title of web page

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#384]
very minor change: 
web browser now shows "action - OCR Form labeling Tool".  
expect: 
    "action - FOTT"

**Comment by alex-krasn** [comment]
We also should update README.md, right?
![image](https://user-images.githubusercontent.com/64093224/86844826-75db0180-c05d-11ea-8870-183c1eb42807.png)

**Comment by xinase** [comment]
I think if we could keep the full name "as is", it's fine.  the bug is complaining "OCR" is leading the title, hence the confusion.
