### ISSUE TITLE
Image URL is badly formatted error

### ISSUE THREAD

**Issue by lukemcredmond** [microsoft/OCR-Form-Tools#389]
**Describe the bug**
Every document i click on generates a "Image URL is badly formatted" pop up

**To Reproduce**
I have pulled the docker container using the following instructions
https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/quickstarts/label-tool#set-up-the-sample-labeling-tool

1. open command prompt and enter "docker run -it -p 3000:80 mcr.microsoft.com/azure-cognitive-services/custom-form/labeltool eula=accept"
2. Click on the saved project
3. Wait for Tags and documetns to load
4. see Error
5. click on any documnet see error

**Expected behavior**
click on the document thumbnail on the left and be able to run the OCR and train.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 version 1909  build 18363.909
 - Docker version [desktop version 2.3.0.3(45519), engine: 19.03.8]
 - Browser chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
blob storage in North Europe
From Recognizer in West US 2
OCR Form Labeling Tool v 2.0.0-0541a32

**Comment by kunzms** [comment]
Hi,

Thanks for reaching out. From the error message, I can see it is an access issue to the documents. We return this error message when the document URL returns 400 Bad Request. Check if the blob container SAS token is still valid (not expired) and has enough permissions (read, write, list and delete).
Also, check if Azure Storage firewall is enabled in your storage account. If it is enabled, then our OCR service cannot access the documents through the SAS token.
[https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security)

**Comment by lukemcredmond** [comment]
i disabled the firewall and i think you are correct.
It is wierd as it could write the json file that was storing the tags etc

also seems to have an issue if there is more than 50 documents

**Comment by kunzms** [comment]
The reason FoTT could write the json file is because it runs on your own machine so it has access. But the train requests are handled on Form Recognizer back end which is blocked.
