### ISSUE TITLE
unhandled rejection when I don't have the project security token for the project I'm trying to load

### ISSUE THREAD

**Issue by stew-ro** [microsoft/OCR-Form-Tools#391]
**Describe the bug**
App crashes when I don't have project security token and I try to load project

**To Reproduce**
1. Go to home page
2. Click on open cloud project
3. Select connection
4. Select project that you don't have a token for

**Expected behavior**
Instead of the app crashing, I expect a clear message displayed to me on how I can add security token

**Screenshots**
![image](https://user-images.githubusercontent.com/60453211/86899526-fb42ce00-c0be-11ea-8111-cfc6387a4af0.png)

**Comment by yongbing-chen** [comment]
update the loadSelectedProject in homePage.tsx

![issuefix#391](https://user-images.githubusercontent.com/68627897/88270877-e7c37400-cd08-11ea-8e32-1342ff6137e1.png)

**Comment by stew-ro** [comment]
Thanks Alex Chen. I created PR #441 with the fix.

By the way, strings should be referenced from strings.ts which are localized in en-us.ts and es-cl.ts
