### ISSUE TITLE
FOTT bug report: Donwload Python code should support 2.0 and 2.1 separately

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#402]
right now it hard-codes to 2.0. 

expect: 
for 2.0 GA, use 2.0,  instead of 2.0-preview

for 2.1 in fott-preview site,  it should use 2.1-preview.1

**Comment by stew-ro** [comment]
This issue was fixed with 63e179d0152d2f8f2ee764443785efa24e5f7dce
