### ISSUE TITLE
FOTT bug report: Prediction result has wrong info. 

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#403]
version 2.1-preview.1-b6719c

in 2.1-preview.1 fott-preview test. 

run analyze on a composed model. 
1) UI shows "model type",   the result json doesn't have model type,  it has "docType". 
2) the text of model name, model Id, DocTypeConfidence should be copy-able,  right now you can't select them and copy the text.

**Comment by stew-ro** [comment]
Yes, I agree. The UI should represent the JSON results

Currently, in the train page UI we're converting confidence result values to percent:
- ![image](https://user-images.githubusercontent.com/60453211/87340197-9b07be00-c4fc-11ea-91c1-a0fd1c41e6fd.png)
- ![image](https://user-images.githubusercontent.com/60453211/87340243-aa870700-c4fc-11ea-85c6-d7c0f3a734c5.png)

Would you prefer it remain converted as a percent in the UI (e.g. 99%)? Or, would you rather it represent the JSON value (e.g. 0.99)?

**Comment by xinase** [comment]
I think it's better to be the same as Json.

**Comment by stew-ro** [comment]
This issue was fixed with 162a7660cfe32b72c4954a147269c5d2b7f55a08
