### ISSUE TITLE
SAS generation issue

### ISSUE THREAD

**Issue by hchintada** [microsoft/OCR-Form-Tools#445]
In readme, in the Create Connections section, for retrieving SAS URI, it says, `To retrieve the SAS URL, open the Microsoft Azure Storage Explorer, right-click your container ... and select Get shared access signature.`

But, when I right click on the container name, I don't get the 'Get shared access signature' option at all.

If I use the SAS generated using the `(Generate SAS)` tab I get after clicking on the blob name, I'm getting the 'Request send error' listing out invalid SAS URI, CORS not confitured and network error.

**Comment by xinase** [comment]
open the Microsoft Azure Storage Explorer,  go to the folder where you store the training files, right click on the folder ... and select "get shared access..."

**Comment by kunzms** [comment]
Updated readme to include a screenshot. I hope this helps.

**Comment by hchintada** [comment]
That solved the issue
