### ISSUE TITLE
Unhandled Rejection (Error): Error parsing JSON

### ISSUE THREAD

**Issue by RohanKittu** [microsoft/OCR-Form-Tools#520]
1) I have cloned this repo and after running the given command , the following GUI popped up.
![image](https://user-images.githubusercontent.com/38404526/91428818-2b674b80-e87c-11ea-885d-f4b0b88590c4.png)

2) So we selected open local projects and uploaded a pdf file for annotating and labeling purposes.But after uploading the following error is popping up.
<img width="1440" alt="Screenshot 2020-08-27 at 3 40 35 PM" src="https://user-images.githubusercontent.com/38404526/91427576-bc89f280-e87b-11ea-9264-526a526a5bec.png">

Kindly help us.

Thank you.

**Comment by stew-ro** [comment]
Hi,

The [Open local project] button is used for opening existing local projects with the .fott extension.

To create a new local project, please do the following:

1. Go to [connections] page
2. Click the [new connection] button
3. Select [local file system] as the provider
4. Select the folder with your pdf files
5. Click save connection
6. Go to [home page] 
7. Click the [new project] button
8. Select created connection as [source connection]

More detailed steps are outlined in the README

**Comment by RohanKittu** [comment]
Thank you.
