### ISSUE TITLE
FOTT bug report

### ISSUE THREAD

**Issue by Ramtirlagni** [microsoft/OCR-Form-Tools#566]
**Describe the bug**
we have hosted the FOTT react code in our servers, and when we tried to create a project in it we are getting "error encrypting data - Cannot read property 'importKey' of undefined" this issue was arising when we are using google chrome, but when we used Firefox browser version 66 this issue was not arising and we are able to create project in FOTT application

**To Reproduce**
regular steps to create the project

**Expected behavior**
a project should have been created where can do labeling, we have used public fott preview website there is no issue in chrome also.

**Screenshots**
![image](https://user-images.githubusercontent.com/71084036/92747672-11f8f000-f3a2-11ea-8d56-e520863ae037.png)

**Desktop (please complete the following information):**
 - OS: win 10 pro
 - Docker version
 - Browser : google chrome
 - Version : 81 and 85 both the version we tired

**Comment by hurricanehrndz** [comment]
I can confirm the same issue using Edge.

**Comment by Ramtirlagni** [comment]
finally i found the issue, the FOTT application where i hostes it was http, so in this url when we tried to create a project we are getting that error because crypto.subtle isn't available over http, So I have used this tool over https so now i am able to create a project and use it in any browser.
Thanks

**Comment by hurricanehrndz** [comment]
@Ramtirlagni Thanks for the information anything special to get going with https?
