### ISSUE TITLE
on-prem: electron app, need to replace "Azure blob storage" text with appropriate "local file system" text

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#570]
**Describe the bug**
on-prem set up, running FoTT on-prem, sometime you see error messages mentioning “Azure Blog Storage"

**Expected behavior**
the error message should be "Local File System",  or something appropriate for on-prem scenario.

**Comment by alex-krasn** [comment]
![image](https://user-images.githubusercontent.com/64093224/92942537-73eb4100-f406-11ea-9414-5c90ffd1f9af.png)
