### ISSUE TITLE
Searching causes exception bug report

### ISSUE THREAD

**Issue by smf723** [microsoft/OCR-Form-Tools#610]
**Describe the bug**
I have a large number of field labels (133) and when I attempt to search through them I get an exception with a dialog stating "Error Loading Application An error occurred while rendering the application. Please try again".

**To Reproduce**
1. Click on the spyglass
2. Start typing a tag name
3. It doesn't always crash but it does at least half the time

**Expected behavior**
A filtered list of tags should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/10367805/94182572-34454000-fe6f-11ea-9701-73c8c06496cc.png)

**Desktop (please complete the following information):**
OS: Win10
Docker version: 2.3.0.4
Browser: chrome
Version: 85

**Comment by stew-ro** [comment]
Hello

Thank you for reporting this bug. Can you please share what version of the FOTT you're using: v2.0-GA or v2.1-Preview. And, also please share it's current commit hash. These can be found at the bottom right of FOTT:
![image](https://user-images.githubusercontent.com/60453211/94187826-6188f280-fe5d-11ea-9bb0-410614ed78e3.png)

Thank you

**Comment by smf723** [comment]
This issue actually happens with V2.0 or V2.1. For V2.0 it's b148062. For V2.1 it's b92b73b. I think bug probably exists in all versions. One thing to note as I was trying to reproduce this issue it usually doesn't happen the first time I search.

Steps to reproduce:
1. Click the spyglass and type in part of a tag name
2. Perform any edit action on one of the shown tags (e.g. select Rename tag but then just hit escape to not change it).
3. Put focus back into the search box, clear the existing search value and start typing again. I usually have to type about 3 letters before it crashes.

It's very consistent with the above steps. Let me know if you still can't reproduce it.

**Comment by smf723** [comment]
BTW, in this latest version of V2.1 (b92b73b) you can no longer drag the form around in the editor. It was working in 530545c.

**Comment by stew-ro** [comment]
Thanks. I was able to reproduce the error given your steps. We'll make the fix shortly and keep you posted

> BTW, in this latest version of V2.1 ([b92b73b](https://github.com/microsoft/OCR-Form-Tools/commit/b92b73bb8076f9b9bb55dd38fcd223b7b93eaa2e)) you can no longer drag the form around in the editor. It was working in [530545c](https://github.com/microsoft/OCR-Form-Tools/commit/530545c7cd2b4a3ff444e9c7e1f40c68d4a7376c).

This was fixed with 77620ec

**Comment by stew-ro** [comment]
This issue should be fixed with cac1e8e. Please let us know if this issue still persists after pulling the latest change and we'll reopen this issue.

Thank you for reporting this
