### ISSUE TITLE
How do I compose specific models with cURL/HTTP and not FOTT?

### ISSUE THREAD

**Issue by emelus** [microsoft/OCR-Form-Tools#658]
From the 2.1 preview API web page, it seems that the codes does not have an option to specify the model IDs, unlike in the FOTT, where we can select the models? This implicates that all models would be composed? (Not the latest x number, or something?) 

https://westcentralus.dev.cognitive.microsoft.com/docs/services/form-recognizer-api-v2-1-preview-1/operations/Compose

I'm really sorry if I'm in the wrong place

**Comment by xinase** [comment]
the body should be model ids, with an optional model name, for example: 
{modelIds: ["167a1110-6006-4811-9d3c-6ab110d1de5d", "28b87cc1-515f-4bcf-83b9-048661d8f60c", "eaa04de3-12f0-4d89-a8cb-8cd3a2b62bc1"]}

**Comment by XinxingLiu** [comment]
In addition to the example above, you might find this swagger page useful: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.1-preview.1/FormRecognizer.json

**Comment by emelus** [comment]
That's perfect. Thanks.
