### ISSUE TITLE
After running Layout on all documents (bugbash)

### ISSUE THREAD

**Issue by alex-krasn** [microsoft/OCR-Form-Tools#685]
**Describe the bug**
After running Layout an all documents FoTT **sometimes** does not ends (the spinner and backdrop does not goes away) after Layout been ran on all documents, thus user can't interact with the tool - spinne and backdrop never goes away.

**Expected behavior**
Should close the spinner everytime when Layout is done.
**Screenshots**
![image](https://user-images.githubusercontent.com/64093224/98152283-52e32180-1e86-11eb-9e0f-dbfbacb5f82c.png)

**Comment by XinxingLiu** [comment]
@stew-ro do you have a stable repro?

**Comment by stew-ro** [comment]
> @stew-ro do you have a stable repro?

I'm not sure what is being described in this issue. @alex-krasn can you clarify?

**Comment by alex-krasn** [comment]
When running Layout (OCR) on all documents - it's never finish the process (stuck in spinner state), but by the state of documents in preview it's clearly visible that all of Layout processes been complete on all documents (no documents left in a queue).

**Comment by XinxingLiu** [comment]
@alex-krasn do you have a stable repro?
