### ISSUE TITLE
"Edit & upload to training set" - does not work

### ISSUE THREAD

**Issue by alex-krasn** [microsoft/OCR-Form-Tools#686]
**Describe the bug**
In feature-3  branch "Edit & upload to training set" - does not work. If it shouldn't be there -then it should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/64093224/98154663-f6820100-1e89-11eb-8fe7-d9337b8a22a0.png)

**Comment by XinxingLiu** [comment]
I guess you are talking about the button on prebuilt model page. The same button on custom form's analyze page works well for me. On prebuilt model page we should remove this button.

**Comment by alex-krasn** [comment]
> I guess you are talking about the button on prebuilt model page. The same button on custom form's analyze page works well for me. On prebuilt model page we should remove this button.

exactly
