### ISSUE TITLE
When running Layout analyze - the app does not prevent leaving

### ISSUE THREAD

**Issue by alex-krasn** [microsoft/OCR-Form-Tools#688]
**Describe the bug**
When use Layout analyze prebuilt model - once user runs Layout, FoTT allows to leave the view in the middle of analysis, thus aborting the operation.

**Expected behavior**
FoTT should prevent leaving when Layout is in progress, and show to user appropriate message. Like this:
![image](https://user-images.githubusercontent.com/64093224/98171737-1377fd80-1ea5-11eb-903f-6cecbebdae28.png)

**Comment by XinxingLiu** [comment]
@alex-krasn could you clarify what does this mean? - "When use Layout analyze prebuilt model"

**Comment by stew-ro** [comment]
> @alex-krasn could you clarify what does this mean? - "When use Layout analyze prebuilt model"

I think he means we need to add a leave confirmation for layout. Similar to what we do for analyze:
![image](https://user-images.githubusercontent.com/60453211/98171407-8cc32080-1ea4-11eb-834c-d31f8397c916.png)

**Comment by alex-krasn** [comment]
1. Go to Analyze Layout: 
![image](https://user-images.githubusercontent.com/64093224/98171504-b1b79380-1ea4-11eb-9503-855b4d7c1e66.png)
2. Start analysis, while still analyzing
3. Switch to another view - no message displayed

**Comment by alex-krasn** [comment]
> > @alex-krasn could you clarify what does this mean? - "When use Layout analyze prebuilt model"
> 
> I think he means we need to add a leave confirmation for layout. Similar to what we do for analyze:
> ![image](https://user-images.githubusercontent.com/60453211/98171407-8cc32080-1ea4-11eb-834c-d31f8397c916.png)

Yes, that's it.
