### ISSUE TITLE
on prebuilt result page, also show table info

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#689]
"display tables on prebuilt result UI"

**Comment by XinxingLiu** [comment]
We are not displaying tables this on custom form's analyze page. Do we also want to do it there?

**Comment by stew-ro** [comment]
> We are not displaying tables this on custom form's analyze page. Do we also want to do it there?

This has been in our to-do backlog for awhile. For the custom form analyze page https://github.com/microsoft/OCR-Form-Tools/issues/202
