### ISSUE TITLE
Error while selecting local file

### ISSUE THREAD

**Issue by stew-ro** [microsoft/OCR-Form-Tools#690]
**Describe the bug**
Error while browsing local files

**To Reproduce**
1. Go to the Layout page
2. Click "Browse for a file..." before any configuration

**Expected behavior**
Display the document

**Screenshots**
![image](https://user-images.githubusercontent.com/60453211/98162193-d5bfa880-1e95-11eb-9ec4-826ee4d2f59f.png)

**Comment by XinxingLiu** [comment]
@stew-ro I cannot repro this bug even if I started private browser and click "browse for a file" before any configuration. How could you reproduce it?

**Comment by XinxingLiu** [comment]
Synced with Robert. After step 2 "Click 'Browse for a file...' before any configuration", we need to select a file to repro this bug.
