### ISSUE TITLE
Prebuilt "Business card" - does not shows results correctly

### ISSUE THREAD

**Issue by alex-krasn** [microsoft/OCR-Form-Tools#691]
**Describe the bug**
Prebuilt "Business card" - does not shows results correctly

**Expected behavior**
Display correct results
**Screenshots**
![image](https://user-images.githubusercontent.com/64093224/98162472-423aa780-1e96-11eb-82f6-1e91d128f080.png)

**Comment by XinxingLiu** [comment]
@yongbing-chen

**Comment by yongbing-chen** [comment]
> @yongbing-chen

the predict result is NaN
