### ISSUE TITLE
Received "InvalidResourceName" when creating new project

### ISSUE THREAD

**Issue by alexmanie** [microsoft/OCR-Form-Tools#778]
**Describe the bug**
When creating a new project, and filling all fields, an error is shown saying:
<code>InvalidResourceName</code>
<Message>The specified resource name contains invalid characters</Message>

**To Reproduce**
1. Create a new project

Example values:
Display Name: aaaaa
Security token: Generate New Security Token
Secure connection: previous blob connection created
Folder path: empty
Forms recognizer url: resource url
API key: resource key1

**Expected behavior**
A new project is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/8184686/99544963-2ca8a000-29b5-11eb-8e2f-9abf88debff0.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome, firefox

**Comment by jrpellicciotti** [comment]
I am also receiving this same message.  I have even deleted all of my setup and recreated it from scratch.  Same message.

**Comment by alexmanie** [comment]
@jrpellicciotti I've resolved by putting the SAS signature directly from Blob Container rather than Storage Account.

Hope this helps.

**Comment by jrpellicciotti** [comment]
Thank you for the information.  I will give it a try.


Rick Pellicciotti | AOD Business Planning Advisor | Component Reliability | FedEx Express | office 901.224.4635 | mobile 901.481.1934 | fedex.com

**Comment by kyle-rader** [comment]
@alexmanie do you know how to create a SAS URL for the blob container in the azure portal? having to write a whole separate program or go find all the needed Powershell to do this programmatically is super annoying. It would be great if we can just parse take the container name as another field on the connection page.

**Comment by alexmanie** [comment]
Thanks for the comments @kyle-rader.
I've closed the issue because I was generation an Storage Account (global resource) SAS instead of a Blob Container SAS token.

Everything works as expected 👍
