### ISSUE TITLE
FOTT bug report: need to update build tag to 2.1-preview.2 in fott-preview

### ISSUE THREAD

**Issue by xinase** [microsoft/OCR-Form-Tools#806]
On the latest https://fott-preview.azurewebsites.net/   

On the bottom-right corner, we have 2 info about version:

V2.1-preview.2   2.1-preview.1-06d9c16

Should the highlighted part be 2.1-preview.2?

**Comment by XinxingLiu** [comment]
Yes. For released version (fott and fott-preview) where API versions are locked down, FoTT version should be in sync with the API version. For internal versions, FoTT version should be in sync with the default API version.
