### ISSUE TITLE
Missing PDF Exception - Unable to load Asset

### ISSUE THREAD

**Issue by Harshil-Kansagara** [microsoft/OCR-Form-Tools#819]
![image](https://user-images.githubusercontent.com/35835271/102214489-5c888c00-3efe-11eb-8c17-a6e0404c8b88.png)

I am using **2.1-preview.2** version in local and deployed a desktop application. I created a project and connected local file system but files are not getting loaded. However all the metadata like generation of *.ocr files and generation of *.fott files does happened properly. Above screenshot is taken using Toggle Developers Tools ON. I also copied URL that it was trying to load and attempted opening in the chrome. It did open there successfully. Please let me know what I'm doing wrong here.

**Comment by benm5678** [comment]
I see same issue.  According to pdfjs repo issue [here](https://github.com/mozilla/pdf.js/issues/12078) they say it's browser limitation.  Could not find workaround yet; I wonder how developers of FOTT got it to work.

**Comment by Harshil-Kansagara** [comment]
Thank you @benm5678. This works for me.

**Comment by AddEleven** [comment]
Hi,

I seem to be getting the same issue. Could you explain the steps to resolve it?

Is it just to run yarn release and then yarn build and yarn start?

I have tried this and it doesnt seem to work..

Thanks,
