### ISSUE TITLE
TypeError : Cannot read property 'GlobalWorkerOptions' of undefined

### ISSUE THREAD

**Issue by pankaj-maurya** [microsoft/OCR-Form-Tools#899]
**Describe the bug**
TypeError: Cannot read property 'GlobalWorkerOptions' of undefined
Module../src/react/components/pages/prebuiltPredict/LoadFileHelper.ts
E:/WORKING_PROJECTS/ATREYA-LABS/OCR-Form-Tools/src/react/components/pages/prebuiltPredict/LoadFileHelper.ts:7
   4 | import HtmlFileReader from "../../../../common/htmlFileReader";
   5 | import {loadImageToCanvas, parseTiffData, renderTiffToCanvas} from "../../../../common/utils";
   6 | 
>  7 | pdfjsLib.GlobalWorkerOptions.workerSrc = constants.pdfjsWorkerSrc(pdfjsLib.version);
   8 | const cMapUrl = constants.pdfjsCMapUrl(pdfjsLib.version);
   9 | 
  10 | export interface ILoadFileResult {

**To Reproduce**
1. run the application by command 'npm run react-start'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5041923/111251384-558c1b00-85cc-11eb-9655-72848d984cca.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Linux-flavor]
 - Docker version

**Additional context**
I tried importing pdfjslib from build folder but that too is not working.

import * as pdfjsLib from "pdfjs-dist/build/pdf";

**Comment by buddhawang** [comment]
Hi @pankaj-maurya,

Thanks for reaching out, it seems `npm` had some issue resolving pdfjs lib. Can you please try using `yarn` as our [README ](https://github.com/microsoft/OCR-Form-Tools#build-and-run-from-source) suggested?

Please let me know if this issue persisted with `yarn`, thanks!

**Comment by pankaj-maurya** [comment]
Hi Buddha,

Thanks for your prompt response.

I tried using `yarn` as README suggested. Followed below steps - 

```
Yarn install
Yarn start
```
But getting same error.

I am using windows 10 ( version : 1909, 64 bit OS) machine  

![image](https://user-images.githubusercontent.com/5041923/111729063-69818800-882b-11eb-95fe-02fa251d212f.png)

**Comment by pankaj-maurya** [comment]
I just downloaded zipped code from repository ant it worked fine.

Hence closing the issue.
