### ISSUE TITLE
Issues with Tools and generated models in version 2.1-preview.3

### ISSUE THREAD

**Issue by alegarro** [microsoft/OCR-Form-Tools#906]
Hi, 

We have a project and use the version with :latest-preview tag in the docker image, and a past few days was updated to the version 2.1-preview.3, after that we have a lot of issues with previous generated models, in the tool and using the generated models with the API.

Our process was the following:

We reuse the labels of the images created with the preview.1 and preview.2 version, after that retrain the model, and test a few images to get the fails in the model, after that I added the image to the training set, and change some autoset labels to another texts, and try to get a new trained model, but in some cases gets the following error:

![image](https://user-images.githubusercontent.com/38103382/111786552-3805cc80-88be-11eb-9650-4efe27030fa2.png)

We get a lot of "Generic Error" try to training, and we can't get a new model.

In another cases, we get an in apparience good trained model, but when we try to use with the 2.1preview API, we get the same "Generic Error".

After downgrade to the preview.2 tool version, all the issues dissapear and we can get new models, and the models are properly used by the API.

Is any problem with the preview.3 version, or perhaps needs to delete all the labels and start again with the labeling and training, or same of our process is wrong?

Thanks in advance.

**Comment by tchekjunior** [comment]
hello, I have same problem with 2.1-preview.3 release.
azure SDK still seems to target  2.1-preview.2 release.

**Comment by alegarro** [comment]
After create a new project and relabel the documents that I have, all start to work again. Close de Issue.
